version: '2'

services:

  elasticsearch:
    build: docker/elasticsearch/
    volumes:
      - ./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

#  logstash:
#    build: docker/logstash/
#    volumes:
#      - ./docker/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
#      - ./docker/logstash/pipeline:/usr/share/logstash/pipeline
#    ports:
#      - "5000:5000"
#    environment:
#      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
#    networks:
#      - elk
#    depends_on:
#      - elasticsearch

  kibana:
    build: docker/kibana/
    volumes:
      - ./docker/kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  nginx:
    build: docker/nginx/
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    links:
      - web
    container_name: nginx

  web:
    build: docker/php-fpm/
    volumes:
      - ./:/var/www/html
    container_name: web

networks:

  elk:
    driver: bridge
